# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MLService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMLService.proto\x12\x0borg.example\"\x19\n\tMLRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\nMLResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x32H\n\tMLService\x12;\n\x08\x63lassify\x12\x16.org.example.MLRequest\x1a\x17.org.example.MLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MLService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MLREQUEST']._serialized_start=32
  _globals['_MLREQUEST']._serialized_end=57
  _globals['_MLRESPONSE']._serialized_start=59
  _globals['_MLRESPONSE']._serialized_end=115
  _globals['_MLSERVICE']._serialized_start=117
  _globals['_MLSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
